name: 'terraform-Azure'

on:
  push:
    branches:
      - main
    paths:
      - "src/terraform/**" # Adjust the path pattern based on your repository structure
  pull_request:
    branches:
      - main
  workflow_dispatch:

defaults:
  run:
    shell: bash

env: 
  ROOT_PATH: '${{github.workspace}}/src/terraform'
  ARM_CLIENT_ID: ${{secrets.AZURE_CLIENT_ID}}
  ARM_CLIENT_SECRET: ${{secrets.AZURE_CLIENT_SECRET}}
  ARM_SUBSCRIPTION_ID: ${{secrets.AZURE_SUBSCRIPTION_ID}}
  ARM_TENANT_ID: ${{secrets.AZURE_TENANT_ID}}
  STAGE_NAME: production

jobs:
  terraform_plan:
    name: 'terraform plan'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.14.0 # Specify a version suitable for your configuration
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
  
    - name: Terraform Init
      run: terraform init
      working-directory: ${{ env.ROOT_PATH }}

    - name: Terraform Plan
      run: terraform plan 
      working-directory: ${{ env.ROOT_PATH }}

  terraform_deploy:
    name: 'Terraform Deploy'
    needs: [terraform_plan]
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.14.0 # Specify a version suitable for your configuration
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
  
    - name: Terraform Init
      run: terraform init
      working-directory: ${{ env.ROOT_PATH }}

    - name: Terraform Apply
      run: terraform apply -auto-approve
      working-directory: ${{ env.ROOT_PATH }}





  
    





          

      

